"""empty message

Revision ID: 189d649f1c2e
Revises: c0a0fd33db1e
Create Date: 2020-08-28 11:54:10.014372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189d649f1c2e'
down_revision = 'c0a0fd33db1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
